# cloudbuild.yaml
steps:
  - name: 'python:3.11'
    id: 'install-deps'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
  # 1. Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/telegram-bot', '.']

  # 2. Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/telegram-bot']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:485.0.0-slim'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'simple-telegram-bot',
        '--image', 'gcr.io/$PROJECT_ID/telegram-bot',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--update-secrets', 'TELEGRAM_TOKEN=TELEGRAM_TOKEN:latest'
      ]

images:
  - 'gcr.io/$PROJECT_ID/telegram-bot'

options:
  logging: CLOUD_LOGGING_ONLY
